### ISSUE TITLE
Syntax error: unexpected token

### ISSUE THREAD

**Issue by kwight** [sirbrillig/gitnews-menubar#2]
Hadn't looked at this for days, but saw this once I did:

![screen shot 2017-07-12 at 12 17 52 pm](https://user-images.githubusercontent.com/349751/28135771-3d1e3492-66fc-11e7-9c8e-9ac693c4cff6.png)

**Comment by sirbrillig** [comment]
Interesting! That sounds like it was trying to pull JSON from the Github API and instead it got HTML. I've seen this happen once before when Github was having an outage. I'll see about adding a check on the response to make sure it's JSON before trying to parse it (created https://github.com/sirbrillig/gitnews/issues/1).

**Comment by sirbrillig** [comment]
Should be fixed now by https://github.com/sirbrillig/gitnews/issues/2 and https://github.com/sirbrillig/gitnews-menubar/commit/5a44de4f32dd4d4777924ceaaf498658c5962fb6
