### ISSUE TITLE
App doesn't open

### ISSUE THREAD

**Issue by shaunandrews** [sirbrillig/gitnews-menubar#42]
This looks super cool, but after installing (and going through the unknown dev thing) the app doesn't seem to do anything. I double click the icon, but nothing shows up in my menu bar.

<img width="236" alt="screen shot 2018-03-08 at 3 22 46 pm" src="https://user-images.githubusercontent.com/191598/37174472-95128e38-22e4-11e8-9f0c-514e399a355d.png">

**Comment by sirbrillig** [comment]
🤔 very likely there's a bug somewhere... if you have time, could you download the git repo and do `npm install && npm start` to see if that does something?

**Comment by sirbrillig** [comment]
Here's the full set of commands to type in the terminal. I should have put this here earlier.

```
git clone https://github.com/sirbrillig/gitnews-menubar.git
cd gitnews-menubar
npm install && npm start
```

That _should_ run the app in developer mode, and if it doesn't start, then you might see some sort of error appear in your terminal. This is very 💩  because I have the app configured to catch errors and display them in a dialog, so I'm not sure what could be causing this, but it'd be lovely to fix it!

**Comment by shaunandrews** [comment]
No luck. Here's what my terminal ended up with:

<img width="1213" alt="screen shot 2018-03-19 at 3 41 37 pm" src="https://user-images.githubusercontent.com/191598/37618238-08221d44-2b8c-11e8-9440-2b8eea38f7df.png">

And here's the contents of the log it mentioned:

> 0 info it worked if it ends with ok
> 1 verbose cli [ '/usr/local/bin/node',
> 1 verbose cli   '/usr/local/bin/npm',
> 1 verbose cli   'run',
> 1 verbose cli   'install-deps' ]
> 2 info using npm@5.5.1
> 3 info using node@v8.9.3
> 4 verbose run-script [ 'preinstall-deps', 'install-deps', 'postinstall-deps' ]
> 5 info lifecycle gitnews-menubar@1.4.0~preinstall-deps: gitnews-menubar@1.4.0
> 6 info lifecycle gitnews-menubar@1.4.0~install-deps: gitnews-menubar@1.4.0
> 7 verbose lifecycle gitnews-menubar@1.4.0~install-deps: unsafe-perm in lifecycle true
> 8 verbose lifecycle gitnews-menubar@1.4.0~install-deps: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/shaunandrews/Documents/Cloned Repos/gitnews-menubar/node_modules/.bin:/usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/shaunandrews/Documents/Cloned Repos/gitnews-menubar/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
> 9 verbose lifecycle gitnews-menubar@1.4.0~install-deps: CWD: /Users/shaunandrews/Documents/Cloned Repos/gitnews-menubar
> 10 silly lifecycle gitnews-menubar@1.4.0~install-deps: Args: [ '-c', 'yarn' ]
> 11 info lifecycle gitnews-menubar@1.4.0~install-deps: Failed to exec install-deps script
> 12 verbose stack Error: gitnews-menubar@1.4.0 install-deps: `yarn`
> 12 verbose stack spawn ENOENT
> 12 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
> 12 verbose stack     at emitTwo (events.js:126:13)
> 12 verbose stack     at ChildProcess.emit (events.js:214:7)
> 12 verbose stack     at maybeClose (internal/child_process.js:925:16)
> 12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
> 13 verbose pkgid gitnews-menubar@1.4.0
> 14 verbose cwd /Users/shaunandrews/Documents/Cloned Repos/gitnews-menubar
> 15 verbose Darwin 17.4.0
> 16 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "install-deps"
> 17 verbose node v8.9.3
> 18 verbose npm  v5.5.1
> 19 error file sh
> 20 error code ELIFECYCLE
> 21 error errno ENOENT
> 22 error syscall spawn
> 23 error gitnews-menubar@1.4.0 install-deps: `yarn`
> 23 error spawn ENOENT
> 24 error Failed at the gitnews-menubar@1.4.0 install-deps script.
> 24 error This is probably not a problem with npm. There is likely additional logging output above.
> 25 verbose exit [ 1, true ]

**Comment by sirbrillig** [comment]
😬 oops, I forgot that yarn was required for development mode. This is the first app I've used it for and I guess this is one of the downsides. 😬 

I really apologize for the trouble, but could you try these instructions instead of the `npm install && npm start` above?

```
npm install && npx electron .
```

**Comment by shaunandrews** [comment]
<img width="161" alt="screen shot 2018-03-20 at 10 17 39 am" src="https://user-images.githubusercontent.com/191598/37660075-ef8084e6-2c27-11e8-89f0-f6c32a749025.png">

Notice anything strange in this screenshot of my menu bar? Maybe if I click in that empty space it'll make sense...

<img width="429" alt="screen shot 2018-03-20 at 10 18 35 am" src="https://user-images.githubusercontent.com/191598/37660134-12c1d1a8-2c28-11e8-839e-f32bbdf5a746.png">

--

So, I think the real issue here is that it doesn't support OS X's "dark mode". Sorry for all the confusion!

**Comment by sirbrillig** [comment]
😂 hah! great find. Thank you for troubleshooting. I've created #43 to track that bug and hopefully I can get the icon to be visible in that mode.
