### ISSUE TITLE
Does not support macOS dark mode

### ISSUE THREAD

**Issue by sirbrillig** [sirbrillig/gitnews-menubar#43]
The icon needs to be white-on-black if we are in dark mode.

Discovered in #42

**Comment by sirbrillig** [comment]
I need to do some research to see how to detect dark mode in Electron, and if I have to include a dark mode icon(s) or if there's some way to just invert the colors...

**Comment by sirbrillig** [comment]
This has a relatively easy fix (see #44) but the issue is that we rely on colorizing the icon for all the statuses, and this does not work when the icon is black-and-white. 

I need to create new icons for the various status cases that can be differentiated without color:

- No notifications ("Normal"; currently all black with no dot)
- Unseen notifications ("Alert"; currently all orange with no dot)
- Seen but unread notifications ("Warn"; currently all black with orange dot)
- Offline ("Offline"; currently all black with red dot)
- Errors ("Error"; currently all red with no dot)

I've never made an icon before so I'd love to get some help with this.

**Comment by michaeldcain** [comment]
Just some ideas - not a designer :). Also, once we agree, happy to make the files.

> No notifications ("Normal"; currently all black with no dot)

How about just an outline of the bell?

> Seen but unread notifications ("Warn"; currently all black with orange dot)

The bell, filled-in.

> Unseen notifications ("Alert"; currently all orange with no dot)

The bell, filled-in, with a dot. Bonus points for a count inside the dot, like the Dropbox "files changed" count.

> Offline ("Offline"; currently all black with red dot)
> Errors ("Error"; currently all red with no dot)

Could we combine these and use the messaging inside the menu to distinguish states? How about the bell with a dot that has an "x" in it.

**Comment by sirbrillig** [comment]
Wow, thanks! I like all these ideas.

I've been playing with some ideas myself, basically trying to get a dot with something inside of it as you suggested. I don't know how to update the icon with a number of notifications right now (I'm guessing maybe the icon would need to be an svg that I can edit on the fly?) so I tried just putting an exclamation point in a dot. Here's the best version of that I could come up with:

![icontemplatenormal-d](https://user-images.githubusercontent.com/2036909/47661746-031f4080-db70-11e8-9d24-63e8a5906238.png)

> Could we combine these and use the messaging inside the menu to distinguish states? How about the bell with a dot that has an "x" in it.

🤔 the reason they're separate is that if I see "Offline" I generally just ignore it since it will probably just be temporary but if I see "Error" I want to look to see what happened. That said, it's probably only relevant for myself since both states might be temporary. I'd be ok with combining them.

**Comment by sirbrillig** [comment]
FWIW icons need to come in two sizes: 32x32 (retina) and 16x16
