### ISSUE TITLE
Requesting Access to System Events

### ISSUE THREAD

**Issue by michaeldcain** [sirbrillig/gitnews-menubar#46]
I updated to Mojave yesterday and received the following:

<img width="532" alt="screen shot 2018-10-17 at 9 16 20 am" src="https://user-images.githubusercontent.com/942359/47095139-a2e8e000-d1fa-11e8-9519-50c0ae302bf1.png">

For what it's worth, I didn't choose and option while I waited to hear back from @sirbrillig about what it was needing, and within 30mins, the prompt went away and the app works as usual.

**Comment by sirbrillig** [comment]
Some quick searching says that this is a new privacy feature of Mojave when apps try to communicate with other apps (eg: applescript). The only thing I can think of is that this is related to the [auto-launch](https://www.npmjs.com/package/auto-launch) module that lets gitnews start when you log in. I'll do more research and see if I can figure anything more out.

**Comment by sirbrillig** [comment]
This might be fixed now that I've removed auto-launch in #97 . Worth testing again.

**Comment by sirbrillig** [comment]
Going to close this unless anyone finds it happening again.
